# Generated by Django 4.2.13 on 2024-05-31 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_item_bid_end_date_collection_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="bid_end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 7, 20, 4, 33, 62816, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
