# Generated by Django 4.2.13 on 2024-06-01 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_item_active_alter_item_bid_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="bid_end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 8, 17, 36, 14, 155074, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
