# Generated by Django 4.2.13 on 2024-06-02 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_item_bid_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="picture",
            field=models.ImageField(default="no-image.svg", null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="item",
            name="bid_end_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 9, 12, 58, 23, 588652, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
